export const CREATE_COURSE: string = "CREATE_COURSE";
export const CREATE_COURSE_SUCCESS: string = "CREATE_COURSE_SUCCESS";
export const UPDATE_COURSE_SUCCESS: string = "UPDATE_COURSE_SUCCESS";
export const LOAD_COURSES_SUCCESS: string = "LOAD_COURSES_SUCCESS";
export const LOAD_AUTHORS_SUCCESS: string = "LOAD_AUTHORS_SUCCESS";
